config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    member do
      delete :purge_avatar
    end
  end
  
  devise_for :users
  root "dashboard#index"
  get 'dashboard/index'

  delete "attachments/:id/purge", to: "attachments#purge", as: "purge_attachment"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  has_one_attached :avatar
  has_many_attached :images

  validates :avatar, attached: true, dimension: { width: { min: 800, max: 2400 } },
    content_type: [:png, :jpg, :jpeg], size: { less_than: 100.kilobytes , message: 'is not given between size' }

  validates :images, attached: true, limit: { min: 1, max: 3 }, content_type: [:png, :jpg, :jpeg, :mp3]

  def to_s
    title
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  def purge
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge
    redirect_back fallback_location: root_path, notice: "success"
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.order(created_at: :desc)
  end

  def purge_avatar
    @post = Post.find(params[:id])
    @post.avatar.purge
    redirect_back fallback_location: root_path, notice: "success"
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :avatar, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SupeRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
        <p>
      <% end %>

      <strong>SupeRails.com</strong>
      <% if user_signed_in? %>
        <%= link_to "Home", root_path, class: "#{'font-weight-bold' if current_page?(root_path)}" %> |
        <%= link_to "Posts", posts_path, class: "#{'font-weight-bold' if controller_name == "posts"}" %> |
        <%= link_to current_user.email, edit_user_registration_path, class: "#{'font-weight-bold' if current_page?(edit_user_registration_path)}" %> |
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "#{'font-weight-bold' if current_page?(new_user_session_path)}" %>
      <% end %>
      
      <hr>

      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, direct_upload: true %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, direct_upload: true %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>
  Posts:
  <%= Post.count %>
</h1>

<%= link_to 'New Post', new_post_path %>

<br>

<div style="overflow-x:auto;">
  <table>
    <thead>
      <tr>
        <th>Id</th>
        <th>Date</th>
        <th>Title</th>
        <th>Content</th>
        <th>Avatar</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.id %></td>
          <td><%= post.created_at.strftime("%d/%H/%Y") %></td>
          <td><%= post.title %></td>
          <td><%= simple_format(post.content) %></td>
          <td><%= image_tag post.avatar, width: "50px" if post.avatar.attached? %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Avatar:</strong>
  <% if @post.avatar.attached? %>
    <%= image_tag @post.avatar, width: "200px" %>
    <%= link_to "Delte avatar", purge_avatar_post_path(@post), method: :delete %>
  <% end %>
</p>

<p>
  <strong>Images:</strong>
  <% if @post.images.attached? %>
    <% @post.images.each do |attachment| %>
      <br>
      <% if attachment.image? %>
        <%= image_tag attachment, width: "200px" %>
      <% elsif attachment.audio? %>
        <audio controls>
          <source src="<%= rails_blob_url(attachment) %>" type="<%= attachment.content_type %>"/>
        </audio>
      <% elsif attachment.video? %>
        <video controls width="480">
          <source src="<%= rails_blob_url(attachment) %>" type="<%= attachment.content_type %>"/>
        </video>
      <% else %>
        <%= link_to attachment.filename, rails_blob_path(attachment, disposition: "attachment") %>
      <% end %>
      <br>
      <%= link_to "Delte attachment", purge_attachment_path(attachment), method: :delete %>
    <% end %>
  <% end %>
</p>

<p>
  <strong>Content:</strong>
  <%= simple_format(@post.content) %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>